//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroVoxel.Properties
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RetroVoxel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Bitmap RVX_RetroVoxelLogo
        {
            get
            {
                object obj = ResourceManager.GetObject("RVX_RetroVoxelLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap RVX_RAConsole
        {
            get
            {
                object obj = ResourceManager.GetObject("RVX_RAConsole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap RVX_LocalSpriteLoader
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_LocalSpriteLoader", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_SpriteSheetSplitter
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_SpriteSheetSplitter", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_RAGameInfo
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_RAGameInfo", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_RABadges
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_RABadges", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_PaletteQuantizer
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_PaletteQuantizer", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_DeltaEFilamentMatcher
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_DeltaEFilamentMatcher", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_PixelGridBuilder
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_PixelGridBuilder", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_VoxelMeshShell
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_VoxelMeshShell", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_MultiMaterialInterlock
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_MultiMaterialInterlock", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_LaserStandoffStack
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_LaserStandoffStack", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_AchievementAttributeBridge
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_AchievementAttributeBridge", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_LegoStudPlate
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_LegoStudPlate", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_PerlerBeadGrid
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_PerlerBeadGrid", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_LEDMatrixMapper
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_LEDMatrixMapper", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_FilamentLibraryLoader
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_FilamentLibraryLoader", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_FindGame
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_FindGame", resourceCulture))); }
        }

        internal static System.Drawing.Bitmap RVX_RAGameImages
        {
            get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("RVX_RAGameImages", resourceCulture))); }
        }
    }
}
